### PR TITLE
Upgrade to Symfony 3.0 

### PR DESCRIPTION
**Pull request by ghost**
Wanted to use this myself but it didn't work on SF3, so I fixed it. 😄

### CODE REVIEW

**Comment by mpalourdio** [comment]
Wow, I didn't know someone was actually using this :D 
Thanks, merging now !

**Comment by ghost** [comment]
Well, this is the first thing I found when searching for `twig twitter symfony`. I disliked using the standard Twitter widget and you give me the option to remove the scrollbar and all, so I like that. I might switch later on, but for now this works fine. 👍 

It should work fine, but I didn't thoroughly test everything. PHPUnit ran without issues and it shows on my website so I've assumed all is correct.

**Comment by mpalourdio** [comment]
Thanks for this feedback. All tests are green, let's trust them for the moment.

I hate the twitter API too. Defaults give poor rendering IMO, that's why I had made this small lib.
Stick to master for the moment, I will try to release tomorrow.

**Comment by ghost** [comment]
Totally agree, thanks for merging so quickly! 

I'll stick with my forked repo for now and I'll remove the line `repositories`-line in `composer.json` once the tag is out.

**Comment by mpalourdio** [comment]
Just released v0.2.0. Enjoy :+1:

**Pull request merged**
